# kubernetes/base/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: zebo-service
spec:
  type: ClusterIP
  selector:
    app: zebo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080